name: Backend Pipeline

on:
  push:
    branches: [ develop, main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports: ['5432:5432']
        env:
          POSTGRES_DB: products
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --prefix backend
      - run: npm test --prefix backend

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          IMAGE_TAG=staging-${{ github.sha }}
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            IMAGE_TAG=prod-${{ github.sha }}
          fi
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/backend:$IMAGE_TAG ./backend
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/backend:$IMAGE_TAG

  deploy-staging:
    needs: build-and-push
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.STAGING_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.STAGING_AKS_CLUSTER }}
      - run: |
          kubectl apply -f k8s/staging/

  deploy-production:
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://myapp-prod.example.com
    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.PRODUCTION_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.PRODUCTION_AKS_CLUSTER }}
      - run: |
          kubectl apply -f k8s/production/
