name: Complete Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main

jobs:
  backend:
    uses: ./.github/workflows/backend-pipeline.yaml

  frontend:
    needs: backend
    uses: ./.github/workflows/frontend-pipeline.yml

  notify:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        run: echo "✅ Complete CI/CD pipeline finished successfully!"
