name: Complete Pipeline

on:
  push:
    branches: [ develop, main ]
  pull_request:

jobs:
  backend:
    uses: ./.github/workflows/backend-pipeline.yml

  frontend:
    needs: backend
    uses: ./.github/workflows/frontend-pipeline.yml
